version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8085:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - product
      - provider
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
      - POSTGRES_HOST_AUTH_METHOD=trust

  product:
    build: ./producto
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://docker:docker@db/docker
    depends_on:
      - db

  provider:
    build: ./proveedor
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://docker:docker@db/docker
    depends_on:
      - db



  